/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import java.util.Calendar;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author assparremberger
 */
public class ListClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListCidades
     */
    
    private JDesktopPane jdpTelaInicial;
            
            
    public ListClientes(JDesktopPane jdpTelaInicial) {
        initComponents();
        carregarTabela();
        this.jdpTelaInicial =  jdpTelaInicial;
    }
    
    public void carregarTabela(){
        List<Cliente> lista = ClienteDAO.getClientes();
        String[] colunas = {"Código", "Nome", "Telefone", "CPF", "Data de Nascimento", "Sexo", "Casado?", "Filhos? "
                + "Salário", "Cidade", "Estado"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(colunas);
        for(Cliente cliente: lista){
            Calendar nasc = cliente.getNascimento();
            String data = ""+
                    nasc.get(Calendar.DAY_OF_MONTH) +
             "/" + (nasc.get(Calendar.MONTH)+1) +
             "/" +  nasc.get(Calendar.YEAR);
            
            String casado = "Não";
            if (cliente.isCasado())
                casado = "Sim";
            String filhos = "Não";
            if (cliente.isTemFilhos())
                filhos = "Sim";
            String sexo = "";
            if (cliente.getSexo().equals("f"))
            sexo = "Feminino";
            if (cliente.getSexo().equals("m"))
                sexo = "Masculino";
            
                    
                    
                    
            
            
            Object[] dados = {
                
                cliente.getCodigo(),
                cliente.getNome(),
                cliente.getTelefone(),
                cliente.getCpf(), data, sexo, casado, filhos, cliente.getSalario(),
                cliente.getCidade().getNome(),
                cliente.getCidade().getEstado().getNome(),
                
                
            };
            
            model.addRow(dados);             
           
        }
        
        tableClientes.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Clientes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Clientes");

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Título 1", "Nome do Cliente"
            }
        ));
        jScrollPane1.setViewportView(tableClientes);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int linha = tableClientes.getSelectedRow();
        if (linha < 0){
            JOptionPane.showMessageDialog(this, "Um cliente deve ser selicionado!");
        }else{
            
            int codigo = (int)tableClientes.getValueAt(linha, 0);
            
            FrmCliente tela = new FrmCliente(codigo, this);
            this.jdpTelaInicial.add(tela);
            tela.setVisible(true);
            
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int linha = tableClientes.getSelectedRow();
        if (linha < 0){
            JOptionPane.showMessageDialog(this, "Um cliente deve ser selicionado!");
        }else{
            
            int codigo = (int)tableClientes.getValueAt(linha, 0);
            Cliente cliente = ClienteDAO.getClienteBycodigo(codigo);
            
            int resposta = JOptionPane.showConfirmDialog(this, " Confirma a exclusão do cliente " + cliente.getNome() + "?","Excluir Cliente",
                     JOptionPane.YES_NO_OPTION);
            
            if (resposta == JOptionPane.YES_NO_OPTION){                
                        
            ClienteDAO.excluir(cliente);
            carregarTabela();
        }
        
        
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
